name: dotnetcore-webapp-ci-cd-k8s

on:
  #push:
  #  branches:
  #    - feature/*
  #    - release/*
  #    - develop
  #pull_request:
  #  branches:
  #    - develop
  #    - main
  workflow_dispatch: 
  
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: Azure/login@v2
      with:
        creds: ${{ secrets.ORG_AZ_CREDENTIALS }}
    
    - name: ACR Login
      run: az acr login --name ${{ vars.ACR_URL }}
    
    - name: Build and Push Docker WEBAPI image
      run: |
        cd src/MyFirstProject.WebApi
        docker build -t ${{ vars.ACR_URL }}/myfirstproject.webapi:${{ GITHUB.RUN_NUMBER }} .
        docker push ${{ vars.ACR_URL }}/myfirstproject.webapi:${{ GITHUB.RUN_NUMBER }}

    - name: Build and Push Docker WEBAPP image
      run: |
        cd src/MyFirstProject.WebApp
        docker build -t ${{ vars.ACR_URL }}/myfirstproject.webapp:${{ GITHUB.RUN_NUMBER }} .
        docker push ${{ vars.ACR_URL }}/myfirstproject.webapp:${{ GITHUB.RUN_NUMBER }}

    - name: View images
      run: docker images
    
    - name: Upload Kubernetes files
      uses: actions/upload-artifact@v4
      with:
        name: k8s
        path: |
          src/MyFirstProject.WebApi/k8s-deployment.yaml
          src/MyFirstProject.WebApp/k8s-deployment.yaml
  
  k8s-dev:
    runs-on: ubuntu-latest
    needs: build-docker
    environment: k8s-dev
    steps:
    # Download k8s artifact
    - name: Download k8s artifact
      uses: actions/download-artifact@v4
      with:
        name: k8s
        path: k8s-artifact

    # Log into Azure
    - name: Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.ORG_AZ_CREDENTIALS }}

    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - name: Deploy set context
      uses: azure/aks-set-context@v4
      with:
        creds: '${{ secrets.ORG_AZ_CREDENTIALS }}'
        cluster-name: ${{ vars.AZ_AKS_NAME }}
        resource-group: ${{ vars.AZ_RG_NAME }}

    # Deploy app to AKS
    - name: Deploy to k8s
      uses: azure/k8s-deploy@v5
      with:
        namespace: default
        manifests: |
          k8s-artifact/MyFirstProject.WebApi/k8s-deployment.yaml
          k8s-artifact/MyFirstProject.WebApp/k8s-deployment.yaml
        images: |
          ${{ vars.ACR_URL }}/myfirstproject.webapi:${{ GITHUB.RUN_NUMBER }}
          ${{ vars.ACR_URL }}/myfirstproject.webapp:${{ GITHUB.RUN_NUMBER }}

  k8s-hml:
    runs-on: ubuntu-latest
    needs: k8s-dev
    environment: k8s-hml
    steps:
    # Download k8s artifact
    - name: Download k8s artifact
      uses: actions/download-artifact@v4
      with:
        name: k8s
        path: k8s-artifact

    # Log into Azure
    - name: Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.ORG_AZ_CREDENTIALS }}

    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - name: Deploy set context
      uses: azure/aks-set-context@v4
      with:
        creds: '${{ secrets.ORG_AZ_CREDENTIALS }}'
        cluster-name: ${{ vars.AZ_AKS_NAME }}
        resource-group: ${{ vars.AZ_RG_NAME }}

    # Deploy app to AKS
    - name: Deploy to k8s
      uses: azure/k8s-deploy@v5
      with:
        namespace: default
        manifests: |
          k8s-artifact/MyFirstProject.WebApi/k8s-deployment.yaml
          k8s-artifact/MyFirstProject.WebApp/k8s-deployment.yaml
        images: |
          ${{ vars.ACR_URL }}/myfirstproject.webapi:${{ GITHUB.RUN_NUMBER }}
          ${{ vars.ACR_URL }}/myfirstproject.webapp:${{ GITHUB.RUN_NUMBER }}
  
  k8s-prd:
    runs-on: ubuntu-latest
    needs: k8s-hml
    environment: k8s-prd
    steps:
    # Download k8s artifact
    - name: Download k8s artifact
      uses: actions/download-artifact@v4
      with:
        name: k8s
        path: k8s-artifact

    # Log into Azure
    - name: Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.ORG_AZ_CREDENTIALS }}

    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - name: Deploy set context
      uses: azure/aks-set-context@v4
      with:
        creds: '${{ secrets.ORG_AZ_CREDENTIALS }}'
        cluster-name: ${{ vars.AZ_AKS_NAME }}
        resource-group: ${{ vars.AZ_RG_NAME }}

    # Deploy app to AKS
    - name: Deploy to k8s
      uses: azure/k8s-deploy@v5
      with:
        namespace: default
        manifests: |
          k8s-artifact/MyFirstProject.WebApi/k8s-deployment.yaml
          k8s-artifact/MyFirstProject.WebApp/k8s-deployment.yaml
        images: |
          ${{ vars.ACR_URL }}/myfirstproject.webapi:${{ GITHUB.RUN_NUMBER }}
          ${{ vars.ACR_URL }}/myfirstproject.webapp:${{ GITHUB.RUN_NUMBER }}
