name: dotnetcore-matrix

on:
  #push:
  #  branches: 
  #    - main
  #    - feature/*
  #  paths-ignore:
  #    - 'docs/**'
  #    - '.github/**'
  workflow_dispatch:

env:
  CONFIGURATION: Release
  
jobs:
  Build:
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '8.0.x' ]
        runner-os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runner-os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Restore dependencies
      run: dotnet restore src/MyFirstProject.sln
    
    - name: Build
      run: dotnet build src/MyFirstProject.sln --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      run: dotnet test src/MyFirstProject.Tests/MyFirstProject.Tests.csproj --no-build --configuration ${{ env.CONFIGURATION }} --verbosity normal --logger "trx;LogFileName=test-results.trx"
    
    - name: Publish APP
      run: dotnet publish src/MyFirstProject.WebApp/MyFirstProject.WebApp.csproj --no-build --configuration ${{ env.CONFIGURATION }} --output ${{ matrix.dotnet-version }}/PublishApp

    - name: Publish API
      run: dotnet publish src/MyFirstProject.WebApi/MyFirstProject.WebApi.csproj --no-build --configuration ${{ env.CONFIGURATION }} --output ${{ matrix.dotnet-version }}/PublishApi

    - name: Upload APP Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact_${{ matrix.dotnet-version }}
        path: ${{ matrix.dotnet-version }}
