name: dotnetcore-webapp-delete-environment

on:
  workflow_dispatch:  
 
jobs:
  Common:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.ORG_AZ_CREDENTIALS }}
    
    - name: Delete Resource Group
      run: |
        if [ $(az group exists --name rg-dotnetproject) = true ]; then
          az group delete --name rg-dotnetproject
        else
            echo "Resource group not exists"
        fi

  Dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.ORG_AZ_CREDENTIALS }}

    - name: Delete Resource Group
      run: |
        if [ $(az group exists --name rg-dotnetproject-dev) = true ]; then
          az group delete --name rg-dotnetproject-dev
        else
            echo "Resource group not exists"
        fi
      
  Hml:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.ORG_AZ_CREDENTIALS }}
    
    - name: Delete Resource Group
      run: |
        if [ $(az group exists --name rg-dotnetproject-hml) = true ]; then
          az group delete --name rg-dotnetproject-hml
        else
            echo "Resource group not exists"
        fi
      
  Prd:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.ORG_AZ_CREDENTIALS }}
    
    - name: Delete Resource Group
      run: |
        if [ $(az group exists --name rg-dotnetproject-prd) = true ]; then
          az group delete --name rg-dotnetproject-prd
        else
            echo "Resource group not exists"
        fi