name: download-artifact

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: RunId
        run: echo  ${{ github.run_id }}
        
      - uses: actions/download-artifact@v4
        with:
           run-id: 12322972171
           repository: prado-org/dotnetcore-webapp
           github-token: ${{ secrets.ORG_GH_PAT }}
           
      - name: Dir
        run: ls -R
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

  
