name: dotnetcore-webapp-iac-reusable

on:
  #push:
  #  branches: [ "main" ]
  #  paths:
  #    - 'iac/**'
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      enableAKS:
        description: 'Enable AKS?'     
        required: true
        type: boolean
        default: false
      enableAPIM:
        description: 'Enable APIM?'     
        required: true
        type: boolean
        default: false
  
jobs:
  Common:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Show Inputs
      run: |
        echo "EnableAks=${{ github.event.inputs.enableAKS }}"
        echo "EnableApim=${{ github.event.inputs.enableAPIM }}"

        echo "AZ_ENABLE_AKS=${{ github.event.inputs.enableAKS }}" >> $GITHUB_ENV
        echo "AZ_ENABLE_APIM=${{ github.event.inputs.enableAPIM }}" >> $GITHUB_ENV
    
    - name: Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.ORG_AZ_CREDENTIALS }}
    
    - name: Generate Resource Group name
      run: |
        rgNAME=rg-${{ vars.AZ_APP_NAME }}
        echo "RG_NAME=$rgNAME" >> $GITHUB_ENV

    - name: Create Resource Group
      run: |
        echo "Resource Group Name is ${{ env.RG_NAME }}"
        echo "Enable AKS is ${{ env.AZ_ENABLE_AKS }}"
        echo "Enable APIM is ${{ env.AZ_ENABLE_APIM }}"
        
        if [ $(az group exists --name ${{ env.RG_NAME }}) = false ]; then
          az group create --name ${{ env.RG_NAME }} --location ${{ vars.AZ_LOCATION }}
        else
            echo "Resource group already exists"
        fi
  
    - name: Create common resources
      uses: Azure/arm-deploy@v2
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RG_NAME }}
        template: iac/main-common.bicep
        deploymentMode: Incremental
        deploymentName: 'gh-actions-common-${{ GITHUB.RUN_NUMBER }}'
        parameters: acrName=${{ vars.AZ_APP_NAME }} location=${{ vars.AZ_LOCATION }} webAppName=${{ vars.AZ_APP_NAME }}
  Dev:
    uses: ./.github/workflows/run-bicep.yml
    with:
      enableAKS: ${{ github.event.inputs.enableAKS }}
      enableAPIM: ${{ github.event.inputs.enableAPIM }}
      AZ_APP_NAME: ${{ vars.AZ_APP_NAME }}
      AZ_LOCATION: ${{ vars.AZ_LOCATION }}
      AZ_ENV_NAME: 'dev'
    secrets:
      ORG_AZ_CREDENTIALS: ${{ secrets.ORG_AZ_CREDENTIALS }}
    needs: Common
      
  Hml:
    uses: ./.github/workflows/run-bicep.yml
    with:
      enableAKS: ${{ github.event.inputs.enableAKS }}
      enableAPIM: ${{ github.event.inputs.enableAPIM }}
      AZ_APP_NAME: ${{ vars.AZ_APP_NAME }}
      AZ_LOCATION: ${{ vars.AZ_LOCATION }}
      AZ_ENV_NAME: 'hml'
    secrets:
      ORG_AZ_CREDENTIALS: ${{ secrets.ORG_AZ_CREDENTIALS }}
    needs: Common
    
  Prd:
    uses: ./.github/workflows/run-bicep.yml
    with:
      enableAKS: ${{ github.event.inputs.enableAKS }}
      enableAPIM: ${{ github.event.inputs.enableAPIM }}
      AZ_APP_NAME: ${{ vars.AZ_APP_NAME }}
      AZ_LOCATION: ${{ vars.AZ_LOCATION }}
      AZ_ENV_NAME: 'prd'
    secrets:
      ORG_AZ_CREDENTIALS: ${{ secrets.ORG_AZ_CREDENTIALS }}
    needs: Common